events {}

http {
  server {
    listen 8080;

    location / {
      limit_except GET HEAD {
        deny all;
      }
      proxy_pass http://fhir-server:9090;
      proxy_set_header Host $host;
    }
  }
}
