[package]
org = "joel"
name = "bff"
version = "0.1.0"
distribution = "2201.13.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.14.1"

[[dependency]]
org = "ballerinax"
name = "mysql.driver"
version = "1.7.0"
