[package]
org = "care_loop"
name = "care_loop_analysis_service"
version = "0.1.0"
distribution = "2201.13.4"

[[dependency]]
org = "care_loop"
name = "care_loop_common"
version = "0.1.0"
repository = "local"

[build-options]
observabilityIncluded = true
